from typing import List

VERSION: str
protocol_handler_packages: List[str]

class SerialException(IOError): ...

class Serial:
    port: str | None
    baudrate: int
    timeout: float | None
    def __init__(
        self,
        port: str | None = None,
        baudrate: int = 9600,
        timeout: float | None = None,
    ) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def read(self, size: int = 1) -> bytes: ...
    def readline(self, size: int = -1) -> bytes: ...
    def write(self, data: bytes) -> int | None: ...
    def reset_input_buffer(self) -> None: ...
    def reset_output_buffer(self) -> None: ...
    @property
    def is_open(self) -> bool: ...

def serial_for_url(url: str, *args: object, **kwargs: object) -> Serial: ...
