from typing import Any, Type, TypeVar

T = TypeVar("T", bound="LittleEndianStruct")

class StructType:
    @staticmethod
    def uint32() -> Any: ...
    @staticmethod
    def uint16() -> Any: ...
    @staticmethod
    def uint64() -> Any: ...
    @staticmethod
    def float32() -> Any: ...
    @staticmethod
    def unsigned_char() -> Any: ...
    @staticmethod
    def chars(size: int) -> Any: ...

class LittleEndianStruct:
    @classmethod
    def unpack(cls: Type[T], data: bytes) -> T: ...
    @classmethod
    def get_size(cls) -> int: ...
